---
ansible_connection: local
openshift_cluster_content:
- galaxy_requirements: "{{ playbook_dir }}/galaxy_requirements.yml"
- object: ci-cd-builds
  content:
  - name: git-bot-secret
    file: "{{ playbook_dir }}/files/secrets/git-bot-secret.yaml"
    namespace: "{{ ci_cd_project.NAMESPACE }}"
    tags:
    - secret
