---
    
    - name: Get Token
      uri:
        url: "{{ cr_sso_url }}"
        method: POST
        headers: 
          Content-Type: "application/x-www-form-urlencoded"
        body: "username={{ cr_user }}&password={{ cr_password }}&grant_type=password&client_id=admin-cli"
        return_content: yes
        status_code: 200
      register: token_response
      tags: npm-stack

    - name: Create Stack
      uri: 
        url: "{{ cr_host_url }}/api/stack"
        method: POST
        status_code: 201
        body: "{{ lookup('file', '../do500-raw-config.json') }}"
        body_format: json
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
      register: stack_response
      tags: npm-stack
 
    - debug: 
        msg: "{{ stack_response.json.id }}"

    - name: Create Permissions on stack
      uri: 
        url: "{{ cr_host_url }}/api/permissions"
        method: POST
        status_code: 204
        body: "{{ lookup('template', 'do500-permissions-json.j2') }}"
        body_format: json
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
      tags: npm-stack

    - name: Create Factory
      uri: 
        url: "{{ cr_host_url }}/api/factory"
        method: POST
        status_code: 200
        body: "{{ lookup('file', '../do500-factory.json') }}"
        body_format: json
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
      register: factory_response
      tags: npm-stack  
      
    - debug: 
        msg: "{{ factory_response.json.links }}"      
  