openshift_cluster_content:
- object: projectrequest
  content:
  - name: "gitlab-spaces"
    file: "{{ inventory_dir }}/../projectrequests/gitlab-spaces.yml"
    file_action: create
- object: deployments
  content:
  - name: "gitlab"
    namespace: "gitlab-proj"
    template: "https://raw.githubusercontent.com/rht-labs/labs-ci-cd/v0.1.0/templates/gitlab/template-ldap.json"
    params: "{{ inventory_dir }}/../params/gitlab/deploy_params"
- object: policy
  content:
  - name: scc-gitlab-policy
    template: "https://raw.githubusercontent.com/rht-labs/labs-ci-cd/v0.1.0/templates/scc/template-project-run-anyuid.json"
    params: "{{ inventory_dir }}/../params/policy/scc_params"
