---
- name: Deploy {{ target }} 
  hosts: "{{ target }}"
  vars:
    ci_cd_namespace: mcanoy-ci-cd
    dev_namespace: mcanoy-dev
    test_namespace: mcanoy-demo
    ci_cd_project:
      IMAGE_STREAM_TAG_NAMESPACE: mcanoy-ci-cd
      NAMESPACE: mcanoy-ci-cd
      NAMESPACE_DISPLAY_NAME: "McAnoy: CI/CD" 

    dev_project:
      NAMESPACE: mcanoy-dev
      NAMESPACE_DISPLAY_NAME: "McAnoy: Dev"
    demo_project:
      NAMESPACE: mcanoy-demo
      NAMESPACE_DISPLAY_NAME: "McAnoy: Demo"
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
